language: node_js
node_js:
  - 'node'
env:
  - EXTENSION_ID=hlepfoohegkhhmjieoechaddaejaokhf

# To deploy locally, you'll need to setup all the ENV variables required by `web-ext-submit` and `chrome-webstore-upload-cli`
deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
    branch: master
    # If HEAD isn't already tagged, then release
    #   On cron jobs, or
    #   When triggered via "Trigger build" on https://travis-ci.org/sindresorhus/refined-github/
    condition: ($TRAVIS_EVENT_TYPE = api || $TRAVIS_EVENT_TYPE = cron) && ($(git tag -l --points-at HEAD) = "")

# Setup Travis to be able to push git tags to GitHub
after_success:
  - |
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

    # Decrypt the file containing the private key
    openssl aes-256-cbc \
      -K $encrypted_132e22846a88_key \
      -iv $encrypted_132e22846a88_iv \
         -in ".travis/github_deploy_key.enc" \
      -out "$SSH_FILE" -d

    # Enable SSH authentication
    chmod 600 "$SSH_FILE" \
      && printf "%s\n" \
          "Host github.com" \
          "  IdentityFile $SSH_FILE" \
          "  LogLevel ERROR" >> ~/.ssh/config

    # Set SSH remote
    git remote set-url origin git@github.com:sindresorhus/refined-github.git
