# Copied from https://github.com/notlmn/browser-extension-template/blob/master/.github/workflows/deployment.yml
name: Deployment

on:
  schedule:
    - cron: '42 13 * * */4'
  push:
    tags:
      - "20.*"
      - "21.*"
      - "22.*"
      - "23.*"
      - "24.*"

jobs:

  Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.daily-version.outputs.version }}
      created: ${{ steps.daily-version.outputs.created }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - uses: fregante/daily-version-action@v1
        name: Create tag if necessary
        id: daily-version
      - uses: notlmn/release-with-changelog@v2
        name: Create release with changelog
        with:
          include-range: true
          token: ${{ secrets.GITHUB_TOKEN }}

  Build:
    needs: Version
    if: github.event_name == 'push' || needs.Version.outputs.created
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm test
    - name: Update extensionâ€™s meta
      env:
        VER: ${{ needs.Version.outputs.version }}
      run: |
        echo https://github.com/$GITHUB_REPOSITORY/tree/$VER > distribution/SOURCE_URL.txt
        npm run version
    - uses: actions/upload-artifact@v2
      with:
        path: distribution

  Chrome:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
    - run: cd artifact && npx chrome-webstore-upload-cli@1 upload --auto-publish
      env:
        EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

  Firefox:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
    - run: cd artifact && npx web-ext-submit@4
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
