name: Labeler

on:
  pull_request_target:
    types:
      - opened
      - edited
      - closed
  pull_request_review:
    types:
      - submitted
  issues:
    types:
      - opened
      - edited

jobs:
  title:
    name: Title
    permissions:
      pull-requests: write
      issues: write
    if: ${{ github.event_name != 'pull_request_review' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: fregante/title-to-labels-action@v1
        with:
          token: ${{ github.token }}
      - uses: actions/checkout@v6
      - uses: fregante/keyword-formatter-action@v1
        with:
          token: ${{ github.token }}
          keywords-path: source/features

  add_labels:
    name: Add PR labels
    permissions:
      pull-requests: write
    if: ${{ github.event_name == 'pull_request_target' && github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            const LABELS_TO_INHERIT = ['enhancement', 'bug', 'meta', 'github bug', 'firefox', 'safari', 'mobile'];
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;

            const query = `
              query($owner: String!, $repo: String!, $prNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $prNumber) {
                    closingIssuesReferences(first: 50) {
                      nodes {
                        labels(first: 50) {
                          nodes {
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            const result = await github.graphql(query, { owner, repo, prNumber });

            const { pullRequest } = result.repository;
            const linkedIssues = pullRequest.closingIssuesReferences?.nodes;
            const linkedIssueLabels = new Set(
              linkedIssues?.flatMap(
                linkedIssue => linkedIssue.labels?.nodes.map(label => label.name) ?? []
              )
            );

            const prLabels = [];
            LABELS_TO_INHERIT.forEach(label => {
              if (linkedIssueLabels.has(label)) prLabels.push(label);
            })

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: prLabels,
            });

  check_labels:
    name: Check if PR has labels
    if: ${{ github.event_name == 'pull_request_review' || github.event.pull_request.merged == true }}
    outputs:
      has_labels: ${{ steps.has_labels.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - id: has_labels
        uses: actions/github-script@v8
        with:
          result-encoding: string
          script: |
            const { labels } = context.payload.pull_request;
            return labels.length > 0;

  post_reminder:
    name: Post comment if unlabeled
    permissions:
      pull-requests: write
    needs: check_labels
    if: ${{ needs.check_labels.outputs.has_labels == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: 'To maintainers: Please add labels to this PR'
