name: Labeler

on:
  pull_request_target:
    types:
      - opened
      - edited
      - labeled

jobs:
  check_labels:
    name: Check if PR has labels
    outputs:
      has_labels: ${{ steps.has_labels.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - id: has_labels
        uses: actions/github-script@v8
        with:
          result-encoding: string
          script: |
            const labels = context.payload.pull_request.labels;
            return labels.length > 0;

  determine_labels:
    name: Determine PR labels
    needs: check_labels
    if: ${{ needs.check_labels.outputs.has_labels == 'false' }}
    outputs:
      pr_labels: ${{ steps.labels.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - id: labels
        uses: actions/github-script@v8
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            let isEnhancement = /^`[\w`-]+` - New feature/.test(prTitle) || /^feat:/.test(prTitle);
            let isBugFix = /^`[\w`-]+` - Fix/.test(prTitle) || /^fix:/.test(prTitle);
            if (isEnhancement && isBugFix) return ['enhancement', 'bug'];

            const query = `
              query($owner: String!, $repo: String!, $prNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $prNumber) {
                    closingIssuesReferences(first: 50) {
                      nodes {
                        labels(first: 50) {
                          nodes {
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            const result = await github.graphql(query, { owner, repo, prNumber });
            const { pullRequest } = result.repository;
            const linkedIssues = pullRequest.closingIssuesReferences?.nodes;
            const labelNames = new Set(
              linkedIssues?.flatMap(
                linkedIssue => linkedIssue.labels?.nodes.map(label => label.name) ?? []
              )
            );
            isEnhancement = isEnhancement || labelNames.has('enhancement');
            isBugFix = isBugFix || labelNames.has('bug');

            const prLabels = [];
            if (isEnhancement) prLabels.push('enhancement');
            if (isBugFix) prLabels.push('bug');
            return prLabels;

  assign_labels:
    name: Assign PR labels
    permissions:
      pull-requests: write
    needs: determine_labels
    outputs:
      assigned: ${{ steps.assign.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - id: assign
        uses: actions/github-script@v8
        with:
          result-encoding: string
          script: |
            const prLabels = ${{ needs.determine_labels.outputs.pr_labels }};
            if (prLabels.length === 0) return false;
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const result = await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: prLabels,
            });
            return true;

  add_reminder:
    name: Remind to add labels
    permissions:
      pull-requests: write
    needs: assign_labels
    if: ${{ needs.assign_labels.outputs.assigned == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: reminder
          message: 'To reviewers: please add labels to this PR'

  remove_reminder:
    name: Remove reminder
    permissions:
      pull-requests: write
    needs: check_labels
    if: ${{ needs.check_labels.outputs.has_labels == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: reminder
          delete: true
