name: Labeler

on:
  pull_request_target:
    types:
      - opened
      - edited
      - labeled

jobs:
  title_to_labels:
    name: Map PR title to labels
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: fregante/title-to-labels-action@v1
        with:
          token: ${{ github.token }}

  inherit_labels:
    name: Inherit labels from linked issues
    outputs:
      pr_labels: ${{ steps.labels.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - id: labels
        uses: actions/github-script@v8
        with:
          script: |
            const LABELS_TO_INHERIT = ['enhancement', 'bug', 'meta', 'github bug', 'firefox', 'safari', 'mobile'];

            const query = `
              query($owner: String!, $repo: String!, $prNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $prNumber) {
                    closingIssuesReferences(first: 50) {
                      nodes {
                        labels(first: 50) {
                          nodes {
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            const result = await github.graphql(query, { owner, repo, prNumber });

            const { pullRequest } = result.repository;
            const linkedIssues = pullRequest.closingIssuesReferences?.nodes;
            const linkedIssueLabels = new Set(
              linkedIssues?.flatMap(
                linkedIssue => linkedIssue.labels?.nodes.map(label => label.name) ?? []
              )
            );

            const prLabels = [];
            LABELS_TO_INHERIT.forEach(label => {
              if (linkedIssueLabels.has(label)) prLabels.push(label);
            })
            return prLabels;

  assign_labels:
    name: Assign PR labels
    permissions:
      pull-requests: write
    needs: inherit_labels
    outputs:
      assigned: ${{ steps.assign.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - id: assign
        uses: actions/github-script@v8
        with:
          result-encoding: string
          script: |
            const prLabels = ${{ needs.inherit_labels.outputs.pr_labels }};
            if (prLabels.length === 0) return false;
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const result = await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: prLabels,
            });
            return true;

  add_reminder:
    name: Remind to add labels
    permissions:
      pull-requests: write
    needs: assign_labels
    if: ${{ needs.assign_labels.outputs.assigned == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: reminder
          message: 'To maintainers: Please add labels to this PR'

  remove_reminder:
    name: Remove reminder
    permissions:
      pull-requests: write
    needs: assign_labels
    if: ${{ needs.assign_labels.outputs.assigned == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: reminder
          delete: true
