# These tags were the results of tests in the past and are troublesome

name: No banned git tags

on:
  push:
    tags:
      - hotfix
      - 19.5.18.1333
      - 19.5.18.1335
      - 19.5.18.1919
      - 19.5.19.1032
      - 19.5.25.1548
      - 19.5.25.1923
      - 19.6.13.1034

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - run: git push --delete origin $GITHUB_REF
