name: PR

on:
  pull_request_target:
    types: [closed]

jobs:
  reminder:
    name: Label Reminder
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check if PR has no labels
        id: check
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const labels = context.payload.pull_request.labels;
            return labels.length === 0;

      - name: Post comment if unlabeled
        if: steps.check.outputs.result == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: 'To maintainers: Please add labels to this PR'
