name: PR

on:
  pull_request_target:
    types: [closed]
  pull_request_review:
    types: [submitted]

jobs:
  reminder:
    name: Label Reminder
    if: github.event_name == 'pull_request_review' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check if PR has no labels
        id: check_labels
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const labels = context.payload.pull_request.labels;
            return labels.length === 0;

      - name: Post comment if unlabeled, or fail on third party PRs
        if: steps.check_labels.outputs.result == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ github.token }}
          message: 'To maintainers: Please add labels to this PR'
